### ISSUE TITLE
Support nested quotes

### ISSUE THREAD

**Issue by damnever** [neoclide/coc-pairs#10]
Python has `'''` or `"""` for multi-line string.

Cloud `coc-pairs` add an option like https://github.com/Raimondi/delimitMate/blob/master/doc/delimitMate.txt#L84 ?

**Comment by chemzqm** [comment]
I don't understand what that option means, and coc-pairs tends to keep simple.

For insert `'''`, you can type `'` three times or use snippet to insert them which is recommended.
