### ISSUE TITLE
Insert line when <CR> is pressed

### ISSUE THREAD

**Issue by gbrlsnchs** [neoclide/coc-pairs#13]
When I create a JSON file, the curly braces are autocompleted:
```json
{}
```
When I press `<CR>`, it would be nice if it added a new line inside so I don't have to leave insert mode just to add a new line with `<c-O>`:
```json
{
  <cursor>
}
```

The actual behavior is:
```json
{
}
```

**Comment by chemzqm** [comment]
It's implemented in coc.nvim to work with formatOnType feature from language server, you have to map your `<CR>` like this:
``` vim
 inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```
functions used here are documented in help.

**Comment by gbrlsnchs** [comment]
Cool, I definitely missed that part, I will read README again. Thanks!

**Comment by IndexXuan** [comment]
why still not work ? Using document above !

**Comment by gbrlsnchs** [comment]
@IndexXuan make sure you don't remap it afterwards. I had the same issue because I had the following line after the above remap:
```viml
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
```
This is from the main README, so my guess is that you also have this line in your config.

**Comment by IndexXuan** [comment]
@gbrlsnchs thanks ~
@chemzqm and there are two inoremap of <CR>，which is the best practice and how can we mixed these ? Thanks very much !

**Comment by chemzqm** [comment]
> which is the best practice 

Don't know, what to map for `<CR>` is up to you, not use `on_enter` when you have performance issue.

**Comment by danielo515** [comment]
wow, this makes it very hard to use enter for confirm the autocomplete and also insert a newline between auto-paired symbols

**Comment by jasoncoleusa** [comment]
> wow, this makes it very hard to use enter for confirm the autocomplete and also insert a newline between auto-paired symbols

I can't get this to work as described.  When I set `"coc.preferences.formatOnType": true` in the coc-settings and I have ` inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"` set, it just autocompletes using the first word (which isn't even highlighted).

**Comment by chemzqm** [comment]
@jasontcole it's expected, you should read doc `:h coc#_select_confirm()`

**Comment by chemzqm** [comment]
You have to use `complete_info()` for check and insert `<CR>` for your keymap if you want insert `<CR>` when no complete item selected.

**Comment by jasoncoleusa** [comment]
> You have to use `complete_info()` for check and insert `<CR>` for your keymap if you want insert `<CR>` when no complete item selected.

Edit:  I revert my vimrc to using the Coc example configuration mappings.  It no longer autocompletes when nothing is highlighted, but coc-pairs is not adding the extra <CR>.  When I add the line you provided in https://github.com/neoclide/coc-pairs/issues/13#issuecomment-478752764, that doesn't make it work.

**Comment by chemzqm** [comment]
> but coc-pairs is not adding the extra . 

I can't understand what do mean by extra.
You should understand what should the code does first instead just say not work.

**Comment by jasoncoleusa** [comment]
> When I create a JSON file, the curly braces are autocompleted:
> 
> ```json
> {}
> ```
> 
> When I press `<CR>`, it would be nice if it added a new line inside so I don't have to leave insert mode just to add a new line with `<c-O>`:
> 
> ```json
> {
>   <cursor>
> }
> ```
> 
> The actual behavior is:
> 
> ```json
> {
> }
> ```

Sorry - typo.  I reverted my vimrc's coc mappings to the example mappings in coc's README.  As described by the post's author, coc-pairs is not adding the extra `<CR>`.  As per your response to them:

> It's implemented in coc.nvim to work with formatOnType feature from language server, you have to map your `<CR>` like this:
> 
> ```viml
>  inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
> ```
> 
> functions used here are documented in help.

If I add this line to my vimrc, it doesn't make coc-pairs operate as I was hoping.  Also, I looked at `:h coc#on_enter()` and added the following (after removing the previous mapping):

```
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
                                  \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```

And this to coc-settings:

```
"coc.preferences.formatOnType": true
```

This also did not give me what I was expecting.  If this is not what we are supposed to add, what else is needed to get coc-pairs to add the extra `<CR>` per the original request?

**Comment by jasontcole** [comment]
I just noticed this may be an issue with vim but not with nvim per https://gitter.im/neoclide/coc.nvim?at=5d38d081a0351b1a8c90ff91 

Can you confirm?

**Comment by chemzqm** [comment]
formatOnType requires language server support，and `<cr>` has nothing to do with coc-pairs

**Comment by chemzqm** [comment]
It should work with that keymapping, you should check your keymapping by verbose command

**Comment by jasoncoleusa** [comment]
So when I open up a file and I immediately type `{` and hit `<CR>`, it works as I was hoping with the new lines.  However, if a wait a few seconds for the LSP server to start, as soon as I type `{` and `<CR>` it autocompletes selecting the first (unhighlighted) item.  I'm assuming this behavior is what `:h coc#_select_confirm()` is referring to.  However, its not clear what I do to resolve it (I am not a vim developer just a user).  

```
  coc#_select_confirm()

          Select first completion item if no completion item is selected, then
          confirm the completion.

          Note: for this function to work as expected, either CompleteChanged
          autocmd should exists or only <C-n> and <C-p> should be used to select
          a completion item.

                                                  health#coc#check()
```

What does "CompleteChanged autocmd" refer to?  I am just Googling around to find anything that sticks out.  Do I add this or??

```
    if exists('##CompleteChanged')
      autocmd CompleteChanged *   call s:Autocmd('MenuPopupChanged', get(v:, 'event', {}), win_screenpos(winnr())[0] + winline() - 2)
    endif
```

**Comment by jasoncoleusa** [comment]
> It should work with that keymapping, you should check your keymapping by verbose command

It would be super helpful if you could provide what needs to be used and where.  There are pieces of information scattered around and I can't seem to find any clear answer, especially since I can't understand the help documentation.  I have the following, but it continues to select the first autocomplete item even when not highlighted. 

```
" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current
" position. Coc only does snippet and additional edit on confirm.
" <cr> could be remapped by other vim plugin, try `:verbose imap <CR>`.
if exists('*complete_info')
  inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
else
  inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
endif

inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```

I tried variations of this, like moving the last line to different parts of the `if` code block.  I know the basics of vim but this is over my head.  It would be super valuable to have this functionality.


Edit:

If I remove the `if` block and only leave this for the `<CR>` mapping:

```
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```

`verbose imap <CR>` shows:

```
i  <CR>        * pumvisible() ? coc#_select_confirm() : "\<C-G>u\<CR>\<C-R>=coc#on_enter()\<CR>"
```

In this case, it still selects the first option.  Im using coc-go (with the default LSP - whatever that is)

**Comment by jasoncoleusa** [comment]
So I've been using on a work machine that has its own LSPs installed.  I was referencing those LSP servers in my .vimrc, and I think that is what was causing the weird behavior I was experiencing.  I should've just did minimal vimrc from the beginning >.< I found using the same vimrc worked on my personal laptop without any problems.  Sorry and thank you for trying to help!!

**Comment by mgryal** [comment]
> It's implemented in coc.nvim to work with formatOnType feature from language server, you have to map your `<CR>` like this:
> 
> ```viml
>  inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
> ```
> 
> functions used here are documented in help.

Hello, when I was writing the following code, an extra tab was added when writing a brace
```python
def some_func():
    return jsonify(
            {}
    )  
```

The solution was to add to the end of the line `<tab> <backspace>`
```viml
noremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>\<tab><backspace>"
```
I write it in case it helps someone
