### ISSUE TITLE
How to add custom pairs?

### ISSUE THREAD

**Issue by wookayin** [neoclide/coc-pairs#15]
I wonder how we can add custom pairs specific to filetype or manually.

It roughly relates to `pairs.enableCharacters`, but the coc-settings.json is rather global. I want to enable specific pair characters only for *certain* filetypes, e.g., `$..$` for `tex`. 

Can we add some configuration point like `b:coc_pairs_enabled` as we already have `b:coc_pairs_disabled`? I tried `:call coc#config('pairs.enableCharacters', ["(", "[", "{", "'", "\"", "`", "$"])` for markdown files, but it didn't work as initialization happens once prior to that.

**Comment by chemzqm** [comment]
It's not necessary for `b:coc_pairs_enabled` since there is `b:coc_pairs_disabled`.

> I want to enable specific pair characters only for certain filetypes, e.g., $..$ for tex.

You should use auto expand snippet by use coc-snippets for that.

**Comment by wookayin** [comment]
> It's not necessary for b:coc_pairs_enabled since there is b:coc_pairs_disabled.

Okay, please never mind about `b:coc_pairs_enabled`. But how can we add custom pairs? vim-autopair plugin seems to support this.

> You should use auto expand snippet by use coc-snippets for that.

Can you please elaborate on this, specifically how I can achieve this with `coc-snippets`'s feature? I can't find relevant documentation there. I can use UltiSnip's autoexpand feature, but I guess it wouldn't handle typing of the closing pair (`$`)?

**Comment by krry** [comment]
Weird timing. I was just wondering how to configure `coc-pairs` by `Filetype`, and add custom pairs.

**Comment by chemzqm** [comment]
>  vim-autopair plugin seems to support this.

it's not designed as vim-autopair, and your should be free to use any autopair plugin with coc.nvim.

> but I guess it wouldn't handle typing of the closing pair ($)?

It can load ultisnip snippets, and it support snippet context and regex snippet same as ultisnip.

**Comment by chemzqm** [comment]
Use `b:coc_paires`
