### ISSUE TITLE
coc-pairs breaks repeat with dot

### ISSUE THREAD

**Issue by chiendo97** [neoclide/coc-pairs#16]
I notice coc-pairs breaks some of my frequently vim actions with dot repeat. 

For example: I want to repeat a change by `ciw[change]esc` keystrokes.

First,  `print('foo', 'foo2')`  into `print('foo')`. 

Then I used dot to repeat `ciw[change]esc` keystrokes with other function `print('foo', 'foo2')`, but It never work as I expect.  

`print('foo', 'foo2')` might become into `print('fofooo', 'foo2')` or `print('foo'foo, 'foo2')` depend on where the pointer is. 

I guess coc-pairs might use escape key between my keystrokes so that it also break the repeat action in vim. 
I really appreciate your work with Neovim community, hope this will could be fixed easily. Thank you so much.

**Comment by chemzqm** [comment]
It's because vim can't redo `<left>` and `<right>`, you should use `ca'` to avoid this problem.

**Comment by chiendo97** [comment]
> It's because vim can't redo `<left>` and `<right>`, you should use `ca'` to avoid this problem.

I want to add more details, only [change] made with coc-pairs will break this repeat. Without using coc-pairs, everthing works fine. 

I tested with some other usecases with `ca'` as you suggest but it still fall to repeat change. I think in vim's principle, it should hold all keystrokes `ca'[change-with-or-without-coc-pairs][esc]` or `ci[change-with-or-without-coc-pairs][esc]` as only one change so a dot `.` can repeat that change in other scenario. 

But as you said, vim can't redo `<left>` and `<right>`. Finally, is that any chance for coc-pairs to use `<left>` and `<right>` but still keep all keystrokes in one change or coc-pairs still can work prefectly fine without using `<left>` and `<right>`?

Thank you again.

**Comment by chemzqm** [comment]
You can disalbe  coc-pairs map your `<bs>`, I don't know if there's some way to avoid use `<left>` or `<right>` for remove pairs. Let me know if you found other vim plugin can make redo of remove pairs work.
