### ISSUE TITLE
Pair end key triggers completion when noselect is false

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc-pairs#2]
Expected behavior pair end key (`"` in this case) triggers cursor move to the right. 
Present behavior with `"coc.preferences.noselect": false` setting: completion is triggered.
![bug](https://user-images.githubusercontent.com/29133776/51226542-dfbd9380-191d-11e9-971d-085840442c37.gif)

**Comment by chemzqm** [comment]
Why you type second `"`? It's already inserted.

**Comment by chemzqm** [comment]
It's a feature that insert keymap would always trigger `<C-y>` first when pumvisible.
Use `<C-e>` to hide the pum first if you don't want confirm completion.

**Comment by Avi-D-coder** [comment]
I typed the second `"` in order to move one to the right without arrow keys or switching modes.

VsCode and other editors that insert pairs do not trigger completion. I have never used a vim pairs extension that triggers completion before. The behavior is only present when `"coc.preferences.noselect": false` is set.

How can this behavior be set to mirror other editors? I.E not triggering completion. 

## VScode behavior
![vscode](https://user-images.githubusercontent.com/29133776/51230166-17800780-192d-11e9-88b9-05e0320128eb.gif)

**Comment by chemzqm** [comment]
It's resolved at https://github.com/neoclide/coc.nvim/commit/9ad0cc7d25c1b0d2fcde2b6517a157e7f4278f0b

**Comment by Avi-D-coder** [comment]
Much appreciated.
