### ISSUE TITLE
Pairs does not play well with macros or repeat

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc-pairs#3]
In normal mode type `qm` then insert a paired character `i(<esc>`
output: `()`
Undo then play the macro `@m`
output `(())`

It happens with repeat too.
`i(`
output: `()`
`<del><esc>`
output: `(`
`.`
output ``
Repeat ends up being just delete.

**Comment by chemzqm** [comment]
I've fixed macros problem, the repeat should be problem of vim, you can test it by type `'<left>'<del><esc>` and repeat it by `.`, vim's repeat is broken on `<left>`

**Comment by Avi-D-coder** [comment]
Thanks
