### ISSUE TITLE
Extra pair inserted when replaying macros.

### ISSUE THREAD

**Issue by avalonv** [neoclide/coc-pairs#32]
If I record a macro such as `qq` `i` `this is a test "aaaaa"` `<esc>` `o` `<esc>` `q` , and then replay it with `@q`, CoC inserts an extra `"`.

**Comment by avalonv** [comment]
As a workaround, is there a way to disable a plugin (in this case coc) during macros?

**Comment by fannheyward** [comment]
`:CocList extensions` will list all extensions, tab to fire `disable` action.

**Comment by avalonv** [comment]
Thanks for the reply, but is there a way to do that programmatically?

**Comment by fannheyward** [comment]
`:call CocAction('toggleExtension', 'coc-pairs')`

**Comment by chemzqm** [comment]
Fixed
