### ISSUE TITLE
Extra pair added when appending to single quote

### ISSUE THREAD

**Issue by avalonv** [neoclide/coc-pairs#33]
If there's a lone quote, brace, parentheses, etc coc-pairs inserts two extra quotes instead of just one

Steps to reproduce:

1)  insert a single ` '` in a buffer
2) append to the end of the line with `A` and type `'`
3) two new quotes are inserted, leaving three in total

Expected behavior: a single quote is inserted, closing the pair.

**Comment by yujinyuz** [comment]
@chemzqm Does this have a fix?

I'm also getting the same behavior with backticks (`)

[![asciicast](https://asciinema.org/a/Zt0ok7Mdd5ZY4GjmohqnQwDNN.svg)](https://asciinema.org/a/Zt0ok7Mdd5ZY4GjmohqnQwDNN)
