### ISSUE TITLE
Plugin doesn't work if installed via vim-plug

### ISSUE THREAD

**Issue by jrwrigh** [neoclide/coc-pairs#36]
As the title says. When I install the extension via vim plug:

```Plug 'neoclide/coc-pairs', {'do': 'yarn install --frozen-lockfile'} ```

and try and let it auto pair a `{`, `(`, or `[`, it does nothing. `CocList extensions` shows that the extension is running.

When I install the extension via `CocInstall coc-pairs`, the extension immediately works.

**Comment by chemzqm** [comment]
Can't reproduce

**Comment by jrwrigh** [comment]
I don't know how else to figure this out, but here's a demonstration gif.
![Peek 2019-11-13 13-42](https://user-images.githubusercontent.com/20801821/68802891-0a4eaa80-061c-11ea-88ff-c5c1871904fe.gif)
Note that the error that shows up in this gif is actually the first time I've seen it appear.

Does coc-pairs have any external dependencies that might be running awry?

**Comment by chemzqm** [comment]
No, could be failed with `yarn install`

**Comment by jrwrigh** [comment]
Can confirm it was a issue with yarn (and thus it was an issue with all coc plugins, not just this one). My symbolic links to the yarn binaries had broken for whatever reason. 

I'll also mention that `:echo executable('yarnpkg')` was a very helpful test to make sure things were working correctly.
