### ISSUE TITLE
pairs double-quote at begining of line in vim-scipt files

### ISSUE THREAD

**Issue by astier** [neoclide/coc-pairs#39]
double-quote is used to write comments in vim-scipts. if a double-quote is entered at the beginning of a line in a vim-script no second quote should be added. vscode does it correctly.

**Comment by chemzqm** [comment]
PR welcome.

**Comment by Gee19** [comment]
I still see this behaviour :(

**Comment by fannheyward** [comment]
New release is needed. @chemzqm

**Comment by Gee19** [comment]
New release fixed this 👍
