### ISSUE TITLE
Option for disable feature: Inserting characters instead of paired character when the previous content ends with two inserting characters

### ISSUE THREAD

**Issue by linhusp** [neoclide/coc-pairs#41]
Whenever I call a variable that its length is greater than 2 inside a pair (like when passing variable into a function call), I can't get out of the pair without hit `<CR>`, although I havent touched the auto completion yet.

The reason is some variables are too short and hiting `<TAB>` and auto complete and then `<CR>` is slower than typing myself. I want it always check for jumping out of the pair.

Vscode behavior:
![Peek 2019-12-18 04-35](https://user-images.githubusercontent.com/31442477/71036215-cdf8f780-214f-11ea-95e2-7cde14dce2a8.gif)

coc-nvim:
![Peek 2019-12-18 04-31](https://user-images.githubusercontent.com/31442477/71036053-6fcc1480-214f-11ea-8859-3b52a26c4039.gif)

**Comment by chemzqm** [comment]
```
  inoremap <expr><C-e> pumvisible() ? "\<C-e>" : "\<End>"
```
