### ISSUE TITLE
Incorrect behaviour on JS template literals

### ISSUE THREAD

**Issue by mulholo** [neoclide/coc-pairs#44]
coc-pairs does not recognise JS template literals and fails to add a missing backtick (`) when one is immediately typed next to a function name without a space.

e.g. When the following is typed, no '\`' is added after 'css\`'
```javascript
import { css } from 'styled-components';

const myMixin = css`
// should add another ` above
```

**Comment by chemzqm** [comment]
No

**Comment by mulholo** [comment]
> No

I think you need to be very careful about giving such blunt, uninformative and rude comments on people's contributions. Above is what I consider to be a genuine bug report and I hoped that this issue would be a step towards a useful improvement for COC users.

Responses like this make me very reluctant to carry on using COC and are extremely off-putting to any potential contributors.
