### ISSUE TITLE
Add pairing for Ruby

### ISSUE THREAD

**Issue by AckmanDESU** [neoclide/coc-pairs#5]
I don't know if this is within the scope of this extension but adding functionality similar to the [vim-endwise](https://github.com/tpope/vim-endwise) plugin would be great. The plugin currently has compatibility issues with CoC and I'd rather stop using it if possible.

**Comment by chemzqm** [comment]
It‘s out of scope of this extension, what's the problem when using vim-endwise with coc.nvim?

**Comment by AckmanDESU** [comment]
It's simply the fact that they have conflicting mappings and I'd rather have ONE plugin that does pairs instead of two and no configuration required.

I fixed the mappings by doing:

```viml
let g:endwise_no_mappings = 1

augroup vimrc-ruby-settings
  autocmd!
  autocmd FileType ruby imap <expr> <CR> pumvisible() ? "\<C-Y>\<Plug>DiscretionaryEnd" : "\<CR>\<Plug>DiscretionaryEnd"
augroup END
```

But if it isn't a possibility with this extension then it'll have to do. It seems this extension is mainly for single character pairs and not for more complex stuff like `<!-- -->` etc.



By the way I guess I should create a new issue but at the moment  if I have: `<|>` and press ">", I get `<>|>`. The other pairs work fine so I guess there's some weird issue.

**Comment by chemzqm** [comment]
I've fixed key-mapping for `>`, I suggest use snippet instead of keymap for complex stuff.

**Comment by chemzqm** [comment]
Closing, this extension doesn't intended to improve `<CR>` experience.
