### ISSUE TITLE
<c-h> remove paired characters

### ISSUE THREAD

**Issue by hamsterBiscuit** [neoclide/coc-pairs#50]
<c-h> remove paired characters

can do this feature?

**Comment by chemzqm** [comment]
Create keymapping to bs should work

**Comment by hamsterBiscuit** [comment]
oh, i try it

**Comment by hamsterBiscuit** [comment]
`inoremap <C-h> <BS>`
i have this keymapping, no work

**Comment by hamsterBiscuit** [comment]
i guess，c-h BS not same code for computer，maybe you can use delete function for c-h

**Comment by chemzqm** [comment]
You should not use noremap for this.
