### ISSUE TITLE
keyword autocomplete

### ISSUE THREAD

**Issue by collegeimprovements** [neoclide/coc-pairs#52]
Thanks a lot for this plugin.
It works out of the box and it's great.

Is it possible to provide keyword based autocomplete for languages where `def`, `do`, `end` etc. keywords are used. 
i.e. when we type`def` ... it also put `end` on the third line and put cursor on 2nd line.

Some of this functionality can be achieved by snippets. However it would be really helpful to have `do................end` autocompletion out of the box for languages like `elixir`.

Or this is a non-feature for this plugin ?

**Comment by chemzqm** [comment]
Use snippet plugin.

**Comment by collegeimprovements** [comment]
Wow...... @chemzqm you're really fast...I was just updating the issue description. 
Many of such things can be achieved with snippets. But can we have some completions like `do...end` ?

**Comment by chemzqm** [comment]
No, out of scope, you can create single file extension yourself https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#single-file-extensions
