### ISSUE TITLE
Feature request: Add an empty line when pressing Enter (and the cursor is in between two brackets)

### ISSUE THREAD

**Issue by hatemets** [neoclide/coc-pairs#56]
This is a feature present in VSCode. It enables the user to instantly start typing (without having to create the empty line themselves) after pressing Enter.

Here's an example:

Initial cursor position (pipe represents the cursor):
 `{|}`

1) After pressing Enter in insert mode, this happens
![image](https://user-images.githubusercontent.com/17316944/83978870-10d3a500-a913-11ea-964a-39b3c8c9b36e.png)

2) The desired effect would be as follows:
![image](https://user-images.githubusercontent.com/17316944/83978917-5f813f00-a913-11ea-8990-1177a3ce477a.png)

This would be a really useful feature that would benefit especially those who write a lot of CSS.

**Comment by chemzqm** [comment]
`:h coc#on_enter()`
