### ISSUE TITLE
Duplicate right brace `{}}` when type `{}` 

### ISSUE THREAD

**Issue by linrongbin16** [neoclide/coc-pairs#58]
# Software

In MacOS, install the newest macvim/python3/node with homebrew. Then install coc.nvim and coc-pairs.

# minimum vimrc

Use [vim-plug](https://github.com/junegunn/vim-plug) as plugin manager.

Here's `.vimrc`:

```
source ~/.vim/autoload/plug.vim
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```

Just install `:CocInstall coc-pairs`.

# Description

When I type `{}`, coc-pairs give me one more duplicate `{}}`.
When I type `[]`, coc-pairs give me one more duplicate `[]]`.

When I type `""`, coc-pairs give me just `""`.
When I type `''`, coc-pairs give me just `''`.
When I type `()`, coc-pairs give me just `()`.

# Expect Behaviour

When I type `{}`, coc-pairs give me just `{}`.
When I type `[]`, coc-pairs give me just `[]`.

**Comment by chemzqm** [comment]
Try minimal vimrc.
