### ISSUE TITLE
Duplicate right brace when type `{}` actually give me `{}}`

### ISSUE THREAD

**Issue by linrongbin16** [neoclide/coc-pairs#59]
# Software

In MacOS, install the newest macvim/python3/node with homebrew. Then install coc.nvim and coc-pairs.

# minimum vimrc

Use [vim-plug](https://github.com/junegunn/vim-plug) as plugin manager.

Here's `.vimrc`:

```
source ~/.vim/autoload/plug.vim
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```

Just install `:CocInstall coc-pairs`.

# Description

When I type `{}`, coc-pairs give me one more duplicate `{}}`.
When I type `[]`, coc-pairs give me one more duplicate `[]]`.

When I type `""`, coc-pairs give me just `""`.
When I type `''`, coc-pairs give me just `''`.
When I type `()`, coc-pairs give me just `()`.

# Expect Behaviour

When I type `{}`, coc-pairs give me just `{}`.
When I type `[]`, coc-pairs give me just `[]`.

**Comment by chemzqm** [comment]
Can't reproduce.

**Comment by linrongbin16** [comment]
Let's close it for now, maybe discuss it later.

**Comment by fannheyward** [comment]
Tested with latest master coc, can't reproduce.

**Comment by fagci** [comment]
If write fast, will duplicate (linux, both coc branches)

**Comment by fagci** [comment]
@chemzqm only vim 8.2 patch 1-814, nvim OK

**Comment by linrongbin16** [comment]
@fagcinsk  Yes, when type fast, it duplicate. when type slow, it will not duplicate.

**Comment by chemzqm** [comment]
Can't reproduce on my vim8

**Comment by tammersaleh** [comment]
I'm also seeing this.
