### ISSUE TITLE
Insert close brace on new line if CR is pressed between braces

### ISSUE THREAD

**Issue by thorlucas** [neoclide/coc-pairs#60]
I'm not entirely sure if I'm just missing something in my config here, but there's no way this is desirable:

![braces](https://user-images.githubusercontent.com/25698466/85373263-ddcf0b00-b4e7-11ea-8e51-62ff61d157ed.gif)

*(not sure why the gif is playing much slower here than the original video, sorry for that)*

I have to exit insert mode and press `k` and re enter insert mode and tab in every time I create a new function. That's actually less ergonomic than not having braces inserted at all.

**Comment by chemzqm** [comment]
`:h coc#on_enter()`, this extension insert pairs only
