### ISSUE TITLE
Duplicate pairs when autocomplete menu is open

### ISSUE THREAD

**Issue by mike-lloyd03** [neoclide/coc-pairs#63]
I'm getting duplicate pairs in Vim 8.1.2292. This seems to only appear when an autocomplete suggestion menu is open.

Plugin list:
- coc.vim
- Vim-Jinja2-Syntax
- vim-polyglot
- sensible
- vim-commentary
- vim-surround
- nerdtree

![Duplicates](https://user-images.githubusercontent.com/49411532/87759664-80b33600-c7c3-11ea-968f-3cb725d163ce.gif)

**Comment by chemzqm** [comment]
Try other vim plugins for parirs, I can't reproduce so don't know the reason.
