### ISSUE TITLE
coc补全和coc-pairs有个不舒服的地方

### ISSUE THREAD

**Issue by cosmicethics** [neoclide/coc-pairs#64]
写scheme都是括号，虽然没有支持的lsp但是纯单词补全也很好用，

 有个很难受的地方，比如有个hello单词，(he)，输入he时弹出补全选项，tab选中hello，再输出右括号，会显示(hello))，多了一个右括号。
正常情况需要先按enter取消选项框，但是也可以直接输入接下来要输入的字符，省去了按enter的过程，可不可以做到按右括号的时候，单词右边有右括号只右移一格。

**Comment by chemzqm** [comment]
> 正常情况需要先按enter取消选项框

你自己决定，无法重现你说的问题

**Comment by chemzqm** [comment]
明白你的意思了，不可以
