### ISSUE TITLE
coc-pairs not closing HTML and JSX tags

### ISSUE THREAD

**Issue by niyabits** [neoclide/coc-pairs#65]
I installed coc-pairs with `:CocInstall coc-pairs` and the extension is not working in any files including HTML. So far I have also used it in `.tsx` and it doesn't work.

I expect coc-pairs to close HTML and JSX tags.

![image](https://user-images.githubusercontent.com/36479718/88794948-d83aa400-d1bc-11ea-8a20-9c37925cc1f0.png)

**Comment by niyabits** [comment]
ah my bad, coc-pairs isn't meant for closing html and jsx tags.

**Comment by chemzqm** [comment]
Use xml.vim
