### ISSUE TITLE
Turning off by filetype

### ISSUE THREAD

**Issue by harrisoncramer** [neoclide/coc-pairs#66]
The documentation states that you should use the following command to turn off coc-pairs based on the filetype:

`autocmd FileType markdown let b:coc_pairs_disabled = ['']`

This isn't working for me, coc-pairs is still running in html files. For example

`autocmd FileType markdown let b:coc_pairs_disabled = ['*.html']
`
This isn't working. How can one turn off coc-pairs in html files, for example?

**Comment by yujinyuz** [comment]
`autocmd FileType html let b:coc_pairs_disabled = ['']`

I'd recommend having a `~/.vim/after/ftplugin/html.vim`

and add the following line:

`let b:coc_pairs_disabled = ['']`

**Comment by kuntau** [comment]
> pairs.disableLanguages, list of language ids to disable this extension, default: [].

You should set it in `CocConfig` file
