### ISSUE TITLE
Can't find coc-pair in npmjs registry 

### ISSUE THREAD

**Issue by harisahmed05** [neoclide/coc-pairs#68]
I'm using Fedora 32. When I write `:CocInstall coc-pair` in Vim, I get the following message:
`Install finished - coc-pair Bad response from https://registry.npmjs.org/coc-pair: 404`

The output of "`~$ npm i -g coc-pair`" is:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/coc-pair - Not found
npm ERR! 404 
npm ERR! 404  'coc-pair@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shanto/.npm/_logs/2020-10-05T17_19_43_595Z-debug.log

Edit: Sorry for my stupid mistake. :(

**Comment by fannheyward** [comment]
It's `coc-pairs`.
