### ISSUE TITLE
[Feature Request] Pair colorizer

### ISSUE THREAD

**Issue by luisdavim** [neoclide/coc-pairs#78]
Hi, It would be great if this extension would support something like https://code.visualstudio.com/updates/v1_60#_high-performance-bracket-pair-colorization
There are vim plugins for this like https://github.com/frazrepo/vim-rainbow but since this extension can already find matching pairs it would be great to get all the functionality in one place.

Would this make more sense in the https://github.com/neoclide/coc-highlight extension?

**Comment by chemzqm** [comment]
It doesn't find matched pairs, should be another plugin.
