### ISSUE TITLE
Disable double quotes in the autocomplete window

### ISSUE THREAD

**Issue by pkiluke** [neoclide/coc-pairs#79]
Good afternoon,

I am using coc and coc-pairs, is it possible to disable the closing double quote in the autocomplete window when using the coc plugin in combination with coc-pairs?

For example:
When I type #include ""... and I choose header.h from the autocomplete window it ends up being #include "header.h""

![image](https://user-images.githubusercontent.com/30906882/138739867-028d4580-2755-4835-8b33-156a7f785126.png)
![image](https://user-images.githubusercontent.com/30906882/138740209-c70f7030-c64c-4fb1-985f-a2e24a2b08d5.png)

**Comment by fannheyward** [comment]
Which language server do you use for C/C++? I've tested with coc.nim/clangd, can't reproduce this.

<img width="240" alt="截屏2021-10-26 上午10 45 59" src="https://user-images.githubusercontent.com/345274/138800263-3b19f58a-b721-4a74-9f22-498e84bc2528.png">

after `<cr>` confirm:

<img width="233" alt="截屏2021-10-26 上午10 46 15" src="https://user-images.githubusercontent.com/345274/138800295-b3a2c15d-af1e-4b1b-9a30-5bbb750030bc.png">

**Comment by pkiluke** [comment]
I am using ccls, with clangd it works fine. I will just change to clangd then, thank you.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
