### ISSUE TITLE
Can extra line be given for easy function body writing after { pairing?

### ISSUE THREAD

**Issue by sloppydevil** [neoclide/coc-pairs#83]
## Current experience
when type "{" to start a function body, there is "}" paired. then input "enter", the "}" just followed the cursor onto the next line.
## Expected Experience
input "{", then "} is paired. then input "enter", cursor jumped to a new line below, and "}" goes to the third line. just like VSCode.

!!!: Maybe this is just one configuration somewhere, but can you help? thx so much.

**Comment by chemzqm** [comment]
`:h coc#on_enter()`

**Comment by sloppydevil** [comment]
use grep to search the coc.txt, and find the solution there.

but my :h coc#on_enter(), no help docu. is this due to the way I install nvim? I directly clone the repo to .vim/**/start.
