### ISSUE TITLE
Inconsistent <BS> behavior

### ISSUE THREAD

**Issue by aaronparisi** [neoclide/coc-pairs#89]
if I type `"`, it inserts the closing `"` automatically. However, if I immediately press <BS>, the closing `"` remains. This behavior is not replicated for other pairs, i.e. typing `'<BS>` results in no characters on screen, similarly for `{<BS>`. Note that the output of `verbose imap <bs>` indicates that is being mapped in coc.vim file, specifically `function! coc#_insert_key` (which I believe enables the other, currently-working auto-pairs <BS> behavior)

I am using homebrew-installed vim version 9.0

coc.nvim version: 0.0.82-3014125e 2023-04-11 14:28:54 +0800

**Comment by ArtisticZhao** [comment]
Same as you, only "" not work.
